name: Weekly Build

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 14 * * 1'

jobs:
    delete-weekly-tag:
        name: Delete weekly tag
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - uses: rickstaa/action-create-tag@v1
              id: "tag_create"
              with:
                tag: "weekly"
                force_push_tag: true
                message: "Weekly build"
